#include "TimelineCodegen.h"

#include <QStringList>
#include <QRegularExpression>
#include <algorithm>

namespace TimelineCodegen {

QString generateBody(const TimelineProject& project) {
    // Sort events by startMs so the generated if-else chain is in
    // chronological order.
    QVector<TimelineEvent> ev = project.events;
    std::sort(ev.begin(), ev.end(),
              [](const TimelineEvent& a, const TimelineEvent& b) {
                  return a.startMs < b.startMs;
              });

    QString s;
    // Sentinel block carrying the project JSON for round-trip.
    s += "-- ===== Generated by the timeline editor =====\n";
    s += "-- Edit blocks in the Timeline tab — this region\n";
    s += "-- is regenerated whenever you press \"→ Lua\".\n";
    s += QString(kSentinelOpen) + "\n";
    s += project.toJsonString() + "\n";
    s += QString(kSentinelClose) + "\n\n";

    // Per-event fired flags (so each event fires once per cycle).
    s += "-- One \"fired\" flag per event so it triggers only once per cycle.\n";
    for (int i = 0; i < ev.size(); ++i) {
        s += QString("_tl_fired_%1 = false\n").arg(i);
    }
    s += "\n";

    s += "function Setup()\n";
    s += "    -- Initial state: every channel off, fired flags reset.\n";
    s += "    for c = 1, 4 do\n";
    s += "        zc.ChannelOff(c)\n";
    s += "        zc.SetPower(c, 0)\n";
    s += "    end\n";
    if (!ev.isEmpty()) {
        s += "    -- (fired flags are reset in Loop's wrap-around branch.)\n";
    }
    s += "end\n\n";

    s += "function Loop(time_ms)\n";
    if (project.loop) {
        s += QString("    -- Loop mode ON — wrap simulated time at %1 ms.\n").arg((int)project.cycleMs);
        s += QString("    local cycle_ms = %1\n").arg((int)project.cycleMs);
        s += "    local prev_t = _tl_last_t or 0\n";
        s += "    local t = time_ms % cycle_ms\n";
        s += "    -- Detect wrap to reset the fired flags.\n";
        s += "    if t < prev_t then\n";
        for (int i = 0; i < ev.size(); ++i) {
            s += QString("        _tl_fired_%1 = false\n").arg(i);
        }
        s += "    end\n";
        s += "    _tl_last_t = t\n";
    } else {
        s += "    -- Loop mode OFF — events fire once at their scheduled time.\n";
        s += "    local t = time_ms\n";
    }

    for (int i = 0; i < ev.size(); ++i) {
        const auto& e = ev[i];
        s += QString("\n    if t >= %1 and not _tl_fired_%2 then\n")
                 .arg((int)e.startMs).arg(i);
        s += QString("        _tl_fired_%1 = true\n").arg(i);
        // Apply parameters before firing (in case they changed via slider).
        s += QString("        zc.SetPower(%1, %2)\n").arg(e.channel).arg(e.power.toLuaExpr());
        s += QString("        zc.SetFrequency(%1, %2)\n").arg(e.channel).arg(e.frequency.toLuaExpr());
        s += QString("        zc.SetPulseWidth(%1, %2, %3)\n")
                 .arg(e.channel).arg(e.pulseWidth.toLuaExpr()).arg(e.pulseWidth.toLuaExpr());
        switch (e.type) {
            case TimelineEvent::Pulse:
                s += QString("        zc.ChannelPulseMs(%1, %2)\n").arg(e.channel).arg((int)e.durationMs);
                break;
            case TimelineEvent::On:
                s += QString("        zc.ChannelOn(%1)\n").arg(e.channel);
                break;
            case TimelineEvent::Off:
                s += QString("        zc.ChannelOff(%1)\n").arg(e.channel);
                break;
        }
        if (!e.comment.isEmpty()) {
            // Embed the user's comment so it survives editing the Lua manually.
            QString safe = e.comment;
            safe.replace('\n', ' ');
            s += "        -- " + safe + "\n";
        }
        s += "    end\n";
    }

    s += "end\n";
    return s;
}

TimelineProject extractProject(const QString& source, bool* found) {
    if (found) *found = false;

    int openPos = source.indexOf(kSentinelOpen);
    if (openPos < 0) return TimelineProject{};
    int jsonStart = openPos + qstrlen(kSentinelOpen);
    int closePos = source.indexOf(kSentinelClose, jsonStart);
    if (closePos < 0) return TimelineProject{};

    QString payload = source.mid(jsonStart, closePos - jsonStart).trimmed();
    auto p = TimelineProject::fromJsonString(payload);
    if (found) *found = true;
    return p;
}

QString updateSentinel(const QString& source, const TimelineProject& project) {
    int openPos = source.indexOf(kSentinelOpen);
    QString jsonLine = project.toJsonString();
    QString block = QString(kSentinelOpen) + "\n" + jsonLine + "\n" + kSentinelClose;

    if (openPos >= 0) {
        int closePos = source.indexOf(kSentinelClose, openPos);
        if (closePos < 0) return source;
        int closeEnd = closePos + qstrlen(kSentinelClose);
        QString out = source;
        out.replace(openPos, closeEnd - openPos, block);
        return out;
    }
    // Insert before the first `function` definition (or at end if none).
    QRegularExpression fnRe(R"(\bfunction\s+\w+\s*\()");
    auto m = fnRe.match(source);
    int insertPos = m.hasMatch() ? m.capturedStart() : source.length();
    QString out = source;
    out.insert(insertPos, block + "\n\n");
    return out;
}

}  // namespace TimelineCodegen
